FROM adoptopenjdk/openjdk11:alpine

ENV APP_HOME=/app/
WORKDIR $APP_HOME

COPY ./insecurity/backend/build.gradle ./insecurity/backend/settings.gradle ./insecurity/backend/gradlew $APP_HOME
COPY ./insecurity/backend/gradle $APP_HOME/gradle

RUN ./gradlew getDeps

RUN rm -rf /app
