
FROM node:lts-alpine AS build

WORKDIR /app

COPY ./insecurity/frontend/package.json ./insecurity/frontend/yarn.lock /app/
RUN yarn install

COPY ./insecurity/frontend/src /app/src
COPY ./insecurity/frontend/public /app/public
RUN yarn build

FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
