
FROM node:lts-alpine AS build

WORKDIR /app

COPY ./package.json ./package-lock.json ./yarn.lock /app/
RUN yarn install

COPY ./src /app/src
COPY ./public /app/public
RUN yarn build

FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

